name: docker
on:
  workflow_dispatch: {}
  release:
    types: [created, edited]
  push: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        pull: true
        push: true
